name: go

on:
  push:
    branches: [main]

jobs:
  go:
    runs-on: ubuntu-20.04
    steps:
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
      - name: Run Unit tests
        run: go test -v -race ./internal/myparser